//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Task_Digital_Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int id_user { get; set; }
        public string login_user { get; set; }
        public string password_user { get; set; }
    }
}
