//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Task_Digital_Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public int file_size { get; set; }
        public string file_path { get; set; }
    }
}
